server:
  port: 8006
spring:
  application:
    name: cloud-consumer-service

ribbon:
  ReadTimeout: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true